server:
  port: 7070

spring:
  application:
    name: gateway

  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: userService
          uri: lb://user-service
          predicates:
            - Path=/user/**,/picture/**,/static/**
        - id: postService
          uri: lb://post-service
          predicates:
            - Path=/post/**
        - id: commentService
          uri: lb://comment-service
          predicates:
            - Path=/comment/**
        - id: messageService
          uri: lb://message-service
          predicates:
            - Path=/message/**
